# -*- coding: utf-8 -*-
"""2702231110 - Edo Kimi Wijaya - Numpy.Linalg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bkANE1AFm5XneK-pkU17LtMw9azkoAKi
"""

import numpy as np

A = np.array ([[4, 3, -5], [-2, -4, 5], [8, 8, 0]])
y = np.array([2, 5, -3])
x = np.linalg.solve(A, y)

print(x)

A_inv = np.linalg.inv(A)

x = np.dot(A_inv, y)
print(x)